"use client"

import 'bootstrap/dist/css/bootstrap.min.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faHouse } from '@fortawesome/free-solid-svg-icons'
import $ from "jquery";
import { React,useState, useEffect } from 'react';
import Table from 'react-bootstrap/Table';
import Sidebaar from '../template/Sidebaar';
import Header from '../template/Header';
import Link from "next/link"
import Pagination from 'react-bootstrap/Pagination';
import axios from 'axios';

const Dashbord=()=>{
    const [userType, setUserType] = useState('')

    const sideCanvasActive= () =>{ 
        $(".expovent__sidebar").removeClass("collapsed");
        $(".expovent__sidebar").removeClass("open");
        $(".app__offcanvas-overlay").removeClass("overlay-open");
    
    }
    const [sideBarAccess, setSideBarAccess] = useState({
        users: false
    });
    const [leadStoreData, setLeadStoreData] = useState([]);
    let active = 2;
    let items = [];
    for (let number = 1; number <= 5; number++) {
    items.push(
        <Pagination.Item key={number} active={number === active}>
        {number}
        </Pagination.Item>,
    );
    }
    const getLeadsData = async () => {

        axios.get(`${process.env.API_BASE_URL}leads.php`)
          .then(res => {
              const data = res.data.leadRecordsData.map((item) => {
                return {
                  id: item.id,
                  clientName: item.clientName,
                  create_at: item.create_at,
                  leadDate:  item.leadDate,
                  leadGenFor: item.leadGenFor,
                  primaryEmail: item.primaryEmail,
                  contactNumber:item.contactNumber,
                  leadGenBy: item.leadGenBy,
                  serviceName: item.serviceName
                }
            }
          )
          setLeadStoreData(data);
        })
        .catch(err => {
         })
     } 

        useEffect(() => {
            if (typeof window !== 'undefined' && window.localStorage) {
               let localType = localStorage.getItem('type');
               if(localType){
                setUserType(localType)
               }  
            }
            getLeadsData();

            }, []);
    return(
        
        <>
         <div className='page_-full-wrapper'>
           <Sidebaar/>
            <div className="app__offcanvas-overlay" onClick={sideCanvasActive}></div>
            <div className="page__body-wrapper">
             <Header />
                <div className="body__overlay"></div>
                <div className="app__slide-wrapper">
                    <div className="row">
                        <div className="col-xl-12">
                            <div className="breadcrumb__wrapper">
                                <div className="breadcrumb__inner">
                                    <div className="breadcrumb__icon">
                                    <FontAwesomeIcon icon={faHouse}/>
                                    </div>
                                    <div className="breadcrumb__menu">
                                        <nav>
                                        <ul>
                                            <li><span><a href="#">Home</a></span></li>
                                            <li className="active"><span>Dashboard</span></li>
                                        </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='row'>
                        <div className='col-xl-12 col-md-12'>
                            <div className='email-serach-box'>
                              <form  className="serach">
                                <input type="text" placeholder="Email"  name="email" value=""/>
                                <button type="button">Search</button>
                                </form>
                              </div>
{                           userType &&userType == 'admin' &&   
                                <div className='add-more'>
                                <Link href='/addmore'>Add More</Link>
                              </div>}
                              <div className='lms-table-wrapp'>
                               <Table striped bordered hover >
                                <thead>
                                    <tr>
                                    <th>S.N.</th>
                                    <th>Lead Generated By</th>
                                    <th>Lead Generated For</th>
                                    <th>Lead Date</th>
                                    <th>Client Name</th>
                                    <th>Service</th>
                                    <th>Email ID</th>
                                    <th>Contact Number</th>
                                    <th>Create At</th>
                                    {/* <th>Contact Number </th> */}
                                    {/* <th>Services</th>
                                    <th>Industry </th>
                                    <th>Country</th>
                                    <th>Generated from Domain/General Ids</th> */}
                                    </tr>
                                </thead>
                                <tbody>
                                {leadStoreData && leadStoreData.length > 0 && leadStoreData.map((lead, l)=>{
                                    return(
                                        <tr key={l}>
                                        <td>{l+1}</td>
                                        <td>{lead.leadGenBy}</td>
                                        <td>{lead.leadGenFor}</td>
                                        <td>{lead.leadDate}</td>
                                        <td>{lead.clientName}</td>
                                        <td>{lead.serviceName}</td>
                                        <td>{lead.primaryEmail}</td>
                                        <td>{lead.contactNumber}</td>
                                        <td>{lead.create_at}</td>                                    
                                    </tr>
                                    )
                                })}
                                </tbody>
                                </Table>
                              </div>
                            <div className='pagination-wrap'>
                                <Pagination>{items}</Pagination>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>
        </>
    )
}
export default Dashbord

